### ISSUE TITLE
Misaligned load and store instructions as performance opportunity

### ISSUE THREAD

**Issue by cmuellner** [riscv/riscv-profiles#40]
The document states `Even when supported, misaligned loads and stores might execute extremely slowly. Standard software distributions should assume their existence only for correctness, not for performance.`.

Fast misaligned loads and stores are an optimization opportunity that is used to implement optimized SW routines on other architectures.

So from SW perspective, it would make sense to have an unsupported optional (but standardized) extension that also includes the performance aspect (i.e. if the extension is available then optimized code for unaligned accesses can be used and can be assumed to result in faster code execution).

This would avoid the need for maintaining a list of mvendorid/marchid entries in multiple SW projects, that decides if misaligned loads and stores are an optimization opportunity.

**Comment by kasanovic** [comment]
This is not an architectural property but rather a performance tuning parameter, and so is best handled by another discovery mechanism (e..g, -mtune, autotuning,etc), not via profile mandates/options.    Even for this single feature, the parameters could be complex (e..g, ,cache-line crossing versus page crossing).  There are potentially a huge number of other features that could also warrant such tuning parameters, and some might even vary depending on which core the thread was currently running in a system with thread migration.  Closing this issue here as this is beyond the scope of profiles.
